repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--unsafe]
      - id: check-xml
      - id: check-json
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
      - id: detect-private-key
      - id: mixed-line-ending
        args: [--fix=lf]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        files: ^custom-addons/
      - id: ruff-format
        files: ^custom-addons/

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.7
    hooks:
      - id: bandit
        args: ['-c', 'pyproject.toml', '-r']
        additional_dependencies: ['bandit[toml]']
        files: ^custom-addons/
        exclude: /tests/

  - repo: https://github.com/OCA/pylint-odoo
    rev: v9.1.2
    hooks:
      - id: pylint_odoo
        args:
          - --disable=all
          - --enable=odoolint
          - --valid-odoo-versions=19.0
        files: ^custom-addons/
        additional_dependencies:
          - pylint-odoo

default_language_version:
  python: python3.10

ci:
  autofix_commit_msg: 'style: auto-fix by pre-commit hooks'
  autoupdate_commit_msg: 'chore: update pre-commit hooks'
